# Generated by Django 4.0.1 on 2022-01-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proizvodi', '0002_products_novi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
